# Generated by Django 4.0.5 on 2022-06-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(default='', null=True)),
                ('image', models.ImageField(upload_to='')),
                ('repo_link', models.URLField()),
                ('deployed_link', models.URLField()),
            ],
        ),
    ]
